### ISSUE TITLE
Failed Upgrade when only using 1 member node. 

### ISSUE THREAD

**Issue by ndmikkelsen** [jfrog/JFrog-Cloud-Installers#17]
Upgrade process fails when only using 1 member node.

2019-03-29 15:47:42,542 [art-init] [INFO ] (o.a.v.c.v.ConanV2DefaultLayoutConverter:58) - Conan default repository layout v2 conversion finished successfully
2019-03-29 15:47:42,676 [art-init] [ERROR] (o.a.c.ConvertersManagerImpl:216) - Conversion failed. You should analyze the error and retry launching Artifactory. Error is: unstable environment: Found one or more servers with different version Config Reload denied.
2019-03-29 15:47:42,679 [art-init] [ERROR] (o.a.w.s.ArtifactoryContextConfigListener:96) - Application could not be initialized: unstable environment: Found one or more servers with different version Config Reload denied.
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.configure(ArtifactoryContextConfigListener.java:211)
        at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.access$200(ArtifactoryContextConfigListener.java:67)
        at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener$1.run(ArtifactoryContextConfigListener.java:92)
Caused by: java.lang.RuntimeException: unstable environment: Found one or more servers with different version Config Reload denied.
        at org.artifactory.converter.ConvertersManagerImpl.handleException(ConvertersManagerImpl.java:223)
        at org.artifactory.converter.ConvertersManagerImpl.serviceConvert(ConvertersManagerImpl.java:171)
        at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:257)
        at org.artifactory.spring.ArtifactoryApplicationContext.<init>(ArtifactoryApplicationContext.java:144)
        ... 7 common frames omitted

**Comment by jfrog-aparicio** [comment]
Closed. Integration deprecated.
