### ISSUE TITLE
Artifactory Upgrades

### ISSUE THREAD

**Issue by darthVikes** [jfrog/JFrog-Cloud-Installers#373]
**Is this a request for help?**:   Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):   No
behavior/change you'd like to see.

**Which installer**:   Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):    Currently on 7.19.4

**Which operating system and version**(eg: ubuntu & version - 20.4):     Ubuntu currently, but migrating to RHEL 9.x

**Which product license** (Enterprise/Pro):  PRO

**JFrog support reference** (if already raised with the support team):    NA

**What happened**:

Should I be able to upgrade to the latest version?    Or do I need to upgrade to X version before going to X version?  aka more step upgrade?

**What you expected to happen**:

Deploy build X and that on startup will upgrade the database information?

**How to reproduce it** (as minimally and precisely as possible):
Tried to upgrade to 7.77.3  but with the migration to another MySQL which requires us to go from 5.x to 8.x  there are some challenges.     Currently, it's giving me a bunch of permissions issues. 

2024-02-07T22:12:21.859Z ^[[1;33m[jfac ]^[[0;39m ^[[1;31m[ERROR]^[[0;39m [23239644096eaeec] [.s.d.u.AccessJdbcHelperImpl:73] [Catalina-utility-2  ] - Could not initialize database:
org.flywaydb.core.api.FlywayException: Detected failed migration to version 7.44 (Add access permission v2 ref)
at org.flywaydb.core.internal.info.MigrationInfoImpl.validate(MigrationInfoImpl.java:218)
at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.validate(MigrationInfoServiceImpl.java:327)
at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:174)
at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:164)
at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:164)
at org.flywaydb.core.Flyway.doValidate(Flyway.java:1017)
at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
at org.flywaydb.core.Flyway$1.execute(Flyway.java:934)
at org.flywaydb.core.Flyway$1.execute(Flyway.java:930)
at org.flywaydb.core.Flyway.execute(Flyway.java:1413)
at org.flywaydb.core.Flyway.migrate(Flyway.java:930)

**Comment by kammathavaran** [comment]
@darthVikes - MySQL upgrades are not part of the ansible upgrade process. What I can suggest is to first upgrade MySQL for 7.19.4 to MySQL 5.7 and subsequently do the upgrade for Artifactory to latest version. 

I'll suggest reaching out [JFrog Support](https://jfrog.com/support/) or [JFrog Community Support ](https://stackoverflow.com/questions/tagged/artifactory)for further help.

**Comment by darthVikes** [comment]
Thanks, the version I have on the new box is Mysql 8.x  also, and I don't see a 5.x version available with RHEL9.   

So doing the export/import with MySQL and I got errors with MySQL not starting, so I tried to do this to get it working with v8 
"mysql --upgrade=FORCE --user=root"   MySQL started after that.  However, I am not sure what it's doing to the tables/data.   

Also, had to put in  /etc/my.cnf (below)  the below to keep innodb engine working which it used to default to in v5, but with v8 it seems to default to MyISAM? 

/etc/my.cnf
# The MySQL server
[mysqld]
innodb=on
innodb_file_per_table=on


However, looking at MySQL and how it is not automated, and finding now the migration steps, wondering if it wouldnt' be better to just use Postgres and use Artifiatory export in Admin to import into Postgres. 

https://jfrog.com/help/r/artifactory-migration-basics/as-part-of-the-migration-we-are-planning-to-switch-to-cloud-storage-how-should-we-copy-the-binaries

https://jfrog.com/help/r/artifactory-what-is-the-best-way-to-migrate-a-large-artifactory-instance-with-minimal-downtime/important-notes
